apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler

metadata:
  name: hpa-blog

spec:
  maxReplicas: 5
  minReplicas: 2 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dep-blog
  targetCPUUtilizationPercentage: 50